### ISSUE TITLE
Texture problems: "swimming", glitches using PRKit, textured polygon

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [asinesio/cocos2d-PRKit#10] opened 2013-03-06 19:38 UTC
I'm creating a car driving game.. and when my car travel the level, where I've created many PRFilledpolygons, I see  "swimming" and glitches effect on the polygons. 
I've created a test project, to reproduce this: http://kamikazeua.narod.ru/test_3.zip
Just start project and touch once a screen, after that screen must start moving so you can see this glitches.  Please take a look carefully. THIS CAN BE REPRODUCED ONLY ON REAL DEVICES.

UPD1: another example, on it this bug can be seen more often: http://kamikazeua.narod.ru/test_2.zip

UPD2 (added 13 march 2:26 GMT+2):   LATEST - some funny car - http://kamikazeua.narod.ru/test_3.zip

**Comment by asinesio** [comment] 2013-03-10 21:36
I've tried to reproduce this on the following devices:

1) iPhone 5 (iOS 6.1.2)
2) iPad Retina - iOS 6.1.2
3) iPad 2 - iOS 6.1.2
4) iPad 1 - iOS 5.1.1

The texture does not "swim", at all, ever.  It works exactly as it should.  I am closing this because it can't be reproduced.

**Comment by Anywhere-Music-Player** [comment] 2013-03-10 21:42
I've just tested again and again, I see this problem.  Try to see closer and more attentive. I also show this to other people and they saw this problem.

**Comment by asinesio** [comment] 2013-03-10 21:45
I've looked very closely. It looks completely fine. Please provide a video if you would like me to investigate further.

**Comment by Anywhere-Music-Player** [comment] 2013-03-10 21:46
Ok, I will try...

**Comment by Anywhere-Music-Player** [comment] 2013-03-10 21:50
And one more question: do you have any jailbreaked device? I just want to send you ipa of my game, so you can install it,   there are many textures and this effect can be really seen. 

10.03.2013, â 23:36, Andy Sinesio notifications@github.com íàïèñàë(à):

**Comment by asinesio** [comment] 2013-03-10 21:51
No, I don't jailbreak devices. Sorry.

**Comment by Anywhere-Music-Player** [comment] 2013-03-10 22:31
Please take a look at this example on real device - http://kamikazeua.narod.ru/test_2.zip
I've modified a polygon and now I can see a really huge swimming. This must be reproducible... 
Just tap to screen after it run on the device and invisible car will drive and texture moves on the screen..

**Comment by Anywhere-Music-Player** [comment] 2013-03-12 21:58
Please run latest test:  http://kamikazeua.narod.ru/test_2.zip  
Also, I see that this problem better can be found if you run without Xcode, just after ipa on the device.
Try also run it several times, because once time I run it, I can't see this problem at all.

**Comment by Anywhere-Music-Player** [comment] 2013-03-13 00:29
UPD2 (added 13 march 2:26 GMT+2):   LATEST - some funny car - http://kamikazeua.narod.ru/test_3.zip

**Comment by slembcke** [comment] 2013-03-14 13:52
Kamikaze asked me to look into this. The "swimming" effect he is talking about is because you are using GL_NEAREST for the texture filtering and the texture coordinates don't quite line up with pixel coordinates:
https://github.com/asinesio/cocos2d-PRKit/blob/master/PRKit/PRFilledPolygon.m#L160

When the screen scrolls slowly, it becomes pretty apparent that this is the case as you get waves of pixels that move across the screen. If you substitute a 50% gray pattern of alternating black/white pixels it becomes painfully apparent.

![aliasing](https://f.cloud.github.com/assets/153633/258915/4c5cc0fe-8cae-11e2-8660-cdf098a8f8a2.png)

**Comment by Anywhere-Music-Player** [comment] 2013-03-14 14:00
slembcke - thank you for the quick reply!  So, what we need to use instead of GL_NEAREST ?

**Comment by slembcke** [comment] 2013-03-14 14:56
If you change that to GL_LINEAR it will solve half of the problem. You'll get subpixel interpolation of the texture, but it will also smear your texture some. In 90% of the cases this isn't a big deal unless you are using pixel art of a very regular pattern like I did in that example image.

As for fixing the texture coordinate alignment issue, I have no idea what is causing that exactly. That would be a lot more work to fix probably.

**Comment by Anywhere-Music-Player** [comment] 2013-03-14 23:59
asinesio, please reopen issue.

**Comment by asinesio** [comment] 2013-03-15 04:52
@slembcke - Thank you so much for your help. I finally was able to see the issue when I used a simpler texture.

@KAMIKAZEUA - I will re-open. I'm not sure when I'll be able to get a fix, but I'm looking at it.

**Comment by asinesio** [comment] 2013-03-16 06:55
This looks to happen because of a precision issue with OpenGL ES. 

The more times the texture repeats, the more "off" it gets.  GL_LINEAR doesn't help any with this specific problem.

See this: http://stackoverflow.com/questions/11370074/opengl-es-2-0-texture-distortion-on-large-geometry-gl-repeat

Your polygon is huge in the example you provided.  Try breaking it into smaller polygons as a workaround.  I'm going to try to address the precision issue.

**Comment by Anywhere-Music-Player** [comment] 2013-03-16 13:58
Yeah, yesterday I was trying to divide the polygons to smaller pieces, but did not get a chance to write about it here.  I also tried to reduce the number of vertices, so after triangulation I get a smaller number of triangles.  

Before: 

![too much vertices](https://f.cloud.github.com/assets/3391456/266844/7b01c206-8e3e-11e2-9ed2-5da9828a38c2.png)

After (less vertices, so less smooth) 

![total breaked and less vertices](https://f.cloud.github.com/assets/3391456/266857/f66037d8-8e3f-11e2-8999-d274395189c4.png)

I tried divide my polygon into  maximum 480px wide polygons, so one part of it looks like this(there some debug lines, pls don't care about them): 

![breaked part](https://f.cloud.github.com/assets/3391456/266862/7226e4de-8e40-11e2-9cf3-58c22a60889b.png)

However problem still occurs.

**Comment by slembcke** [comment] 2013-03-16 20:33
So I dunno if the ES spec gives a minimum texture interpolation precision, (I'd presume it does since it's important) but after a certain range, you can't even store integers anymore. The solution is relatively straightforward if slightly inconvenient. Slice the triangles (easier than at the polygon level) by a grid and take the modulo of the texture coordinates so that you never go outside of a certain range. The ES spec guarantees that mediump should be able to represent ints up to +/- 1024. I can't imagine that texture samplers are allowed less precision than that, so that's maybe a good value.

**Comment by Anywhere-Music-Player** [comment] 2013-03-20 09:08
Same here.. - http://www.levelhelper.org/phpBB3/viewtopic.php?f=7&t=2674&p=15743
Maybe thats cocos2d issue?

**Comment by asinesio** [comment] 2013-03-22 23:59
I really think this is an OpenGL issue possibly combined with a sub-optimal triangulation algorithm (skinny triangles, rather than uniform ones.)  Doing very large polygons on OpenGL ES clearly has major issues.

One way to improve this would be to split the polygon every X times the texture repeats.  This does a few things:
- Prevents the "rounding" error we're seeing in OpenGL by starting a new polygon.
- Improves performance and reduces memory since you can hide/delete the PRFilledPolygons that are off screen.

So, in your example, when you've gone, say, 10x the texture size in width, you create a PRFilledPolygon with what you have to that point, and start a new one using the same texture.  Then simply display them next to each other on screen and you should be good to go.

Can you try that?

**Comment by Anywhere-Music-Player** [comment] 2013-03-23 16:44
Actually about this - about dividing polygons I wrote in previous message - https://github.com/asinesio/cocos2d-PRKit/issues/10#issuecomment-15005231   If I understand you correctly? (Or do you want me change the texture points... so jsut call method "-(void) setPoints: (NSArray *) points" for one PRFilledPolygon every screen...  I need to test this...  )  
Today I've do less triangles again and here is how triangles in one texture looks like: 

![ 2013-03-23 18 31 17](https://f.cloud.github.com/assets/3391456/294157/ee792dec-93d8-11e2-9313-0a329173d79b.png)

However, problem still there.

In my game I have 50000px wide world and it's divided by 480px width texture and they displayed, loaded and deleted one by one in my game. +- 480px from current player point.  
I think same method used in LevelHelper, but it has the same bug, link about this I've posted in my previous message.  Also, what I want to say - that in LH this bug occurs after some time,  for example if world has 20000px width, so swimming will maybe after camera moves far than 10000px+. And with PRKit this problem can be seen in a short time, so in pixels it's maybe 2000px...

**Closed as completed** 2017-05-10 14:08 UTC
Labels: Bug, Can't Reproduce
