### ISSUE TITLE
Problem with Portrait and Landscape texture.

### ISSUE THREAD

**Issue by icanswiftabit** [asinesio/cocos2d-PRKit#8] opened 2012-10-11 22:40 UTC
Hello Ihave a problem with Portrait/Landscape texture. I think it is bad textCord caculation. It's hard to describe so I just show.

That should be Portrait with one image.
![Portrait](http://i50.tinypic.com/2w6f9d2.png)

That should be Landscape with one image.
![Landscape](http://i46.tinypic.com/2prxu1k.png)

any suggestion I will thankful :)

**Comment by asinesio** [comment] 2013-02-27 01:23
Sorry that I have been lax in getting back to you on this issue.  I think it's likely that you are not using square textures. 

The texture size you use needs to be square so that it can properly repeat in vertical and horizontal dimensions.  I'll close this for now, but if you are able to send code that reproduces it, I'll take a look.

For starters, you could try your texture in the provided example project and make sure it repeats properly.

**Closed as completed by asinesio** 2013-02-27 01:23 UTC
Labels: Bug, Can't Reproduce

**Comment by wicharek** [comment] 2013-08-07 07:50
Hi, I am not sure what is the reason for supporting square textures only. But with this small patch non-square textures will also work just fine (at least in my case).

Replace calculateTextureCoordinates method in PRFilledPolygon.m with:

``` Objective-C
-(void) calculateTextureCoordinates {
    for (int j = 0; j < areaTrianglePointCount; j++) {
        GLfloat scaleX = 1.0f/texture.pixelsWide * CC_CONTENT_SCALE_FACTOR();
        GLfloat scaleY = 1.0f/texture.pixelsHigh * CC_CONTENT_SCALE_FACTOR();
        textureCoordinates[j] = (ccVertex2F) { areaTrianglePoints[j].x * scaleX, areaTrianglePoints[j].y * scaleY };
        textureCoordinates[j].y = 1 - textureCoordinates[j].y;
    }
}
```

Nice library, btw, thanks!
